steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/rideapp', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/rideapp']
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'k8s/deployment.yaml'
      - '-f'
      - 'k8s/service.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=YOUR_COMPUTE_ZONE'
      - 'CLOUDSDK_CONTAINER_CLUSTER=YOUR_CLUSTER_NAME'
images:
  - 'gcr.io/$PROJECT_ID/rideapp'
